import mongoose from "mongoose";

/**
 * A saved resume artifact. `kind` distinguishes the three flows:
 *  - 'created'   : generated by AI from a form
 *  - 'checked'   : an uploaded resume that was scored (stores sourceText + score + feedback)
 *  - 'rewritten' : an AI-improved version of an existing resume
 */
const resumeSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    kind: {
      type: String,
      enum: ["created", "checked", "rewritten"],
      required: true,
    },
    title: {
      type: String,
      trim: true,
      default: "Untitled resume",
    },
    // Markdown resume content (for 'created' and 'rewritten').
    content: {
      type: String,
      default: "",
    },
    // Extracted text of an uploaded resume (for 'checked' and as input to 'rewritten').
    sourceText: {
      type: String,
      default: "",
    },
    // Score out of 10 (for 'checked').
    score: {
      type: Number,
      min: 0,
      max: 10,
      default: null,
    },
    // Structured feedback object from the scorer (summary, strengths, weaknesses, suggestions, atsFriendliness).
    feedback: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
  },
  { timestamps: true }
);

resumeSchema.set("toJSON", {
  transform(_doc, ret) {
    delete ret.__v;
    return ret;
  },
});

export const Resume = mongoose.model("Resume", resumeSchema);
