// pdf-parse ships as CommonJS; import its implementation entry directly to avoid
// its index.js debug harness that reads a test file at require time.
import { createRequire } from "module";
import PDFDocument from "pdfkit";
const require = createRequire(import.meta.url);
const pdfParse = require("pdf-parse/lib/pdf-parse.js");

/**
 * Extract plain text from an uploaded PDF buffer.
 * Throws a friendly, tagged error if the PDF has no extractable text
 * (e.g. it's a scanned image).
 */
export async function extractText(buffer) {
  const data = await pdfParse(buffer);
  const text = (data.text || "").trim();

  if (text.length < 30) {
    const err = new Error(
      "We couldn't read any text from that PDF. If it's a scan or image, please upload a text-based PDF."
    );
    err.status = 400;
    throw err;
  }

  return text;
}

/**
 * Generate a professional, ATS-friendly PDF from markdown resume content.
 * Returns a Buffer containing the PDF data.
 */
export function generatePDF(markdownContent) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 50,
      size: "Letter",
      bufferPages: true,
    });

    const chunks = [];

    // Collect PDF data chunks
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Set default font for ATS compatibility
    doc.font("Helvetica");

    // Parse and format the markdown content
    const lines = markdownContent.split("\n");
    let currentSection = null;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const trimmed = line.trim();

      // Skip empty lines but add space
      if (!trimmed) {
        doc.moveDown(0.2);
        continue;
      }

      // H1 - Main title (name) - Large and bold
      if (trimmed.startsWith("# ")) {
        const title = trimmed.replace(/^#+\s*/, "").trim();
        doc.fontSize(16).font("Helvetica-Bold").text(title, {
          align: "center",
        });
        doc.moveDown(0.3);
        // Add a line separator
        doc.strokeColor("#cccccc").lineWidth(0.5).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown(0.3);
      }
      // H2 - Section headers
      else if (trimmed.startsWith("## ")) {
        currentSection = trimmed.replace(/^##\s*/, "").trim();
        doc.fontSize(11).font("Helvetica-Bold").text(currentSection.toUpperCase());
        doc.strokeColor("#000000").lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown(0.2);
      }
      // H3 - Subsection headers (job titles, degree names, etc.)
      else if (trimmed.startsWith("### ")) {
        const subsection = trimmed.replace(/^###\s*/, "").trim();
        doc.fontSize(10).font("Helvetica-Bold").text(subsection);
        doc.moveDown(0.1);
      }
      // H4 - Details (dates, locations)
      else if (trimmed.startsWith("#### ")) {
        const detail = trimmed.replace(/^####\s*/, "").trim();
        doc.fontSize(9).font("Helvetica").fillColor("#666666").text(detail);
        doc.fillColor("#000000");
        doc.moveDown(0.05);
      }
      // Bullet points
      else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
        const bulletText = trimmed.replace(/^[-*]\s*/, "").trim();
        // Clean markdown formatting
        const cleanText = bulletText
          .replace(/\*\*(.*?)\*\*/g, "$1")
          .replace(/_(.*?)_/g, "$1")
          .replace(/\[(.*?)\]\(.*?\)/g, "$1");

        doc.fontSize(10).font("Helvetica").text("• " + cleanText, {
          indent: 10,
          width: 450,
        });
        doc.moveDown(0.05);
      }
      // Regular paragraph text
      else {
        // Clean markdown formatting
        const cleanText = trimmed
          .replace(/\*\*(.*?)\*\*/g, "$1")
          .replace(/_(.*?)_/g, "$1")
          .replace(/\[(.*?)\]\(.*?\)/g, "$1");

        doc.fontSize(10).font("Helvetica").text(cleanText, {
          width: 450,
          align: "left",
        });
        doc.moveDown(0.05);
      }
    }

    // Add footer with generation info (positioned at bottom with more space)
    doc.fontSize(8).fillColor("#999999").text("Generated by ResuMate • ATS-Optimized", {
      align: "center",
      y: doc.page.height - 20,
    });

    doc.end();
  });
}
